logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

server:
  port: 8081

okta:
  oauth2:
    issuer: https://dev-02872244.okta.com/oauth2/default
    client-id: 0oa6ahiv9iWNyclGA5d7
    client-secret: J3hOLi-UlI8uy92GR3783BankWajGqPwiYbdU4RO
    #redirect-uri: /authorization-code/callback
