logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

server:
  port: 8081

okta:
  oauth2:
    issuer: https://dev-02872244.okta.com/oauth2/default
    client-id:  
    client-secret:  
    #redirect-uri: /authorization-code/callback
